"variable" "label"
"1" "abuse" "=1 if abuse alcohol"
"2" "status" "out of workforce = 1; unemployed = 2, employed = 3"
"3" "unemrate" "state unemployment rate"
"4" "age" "age in years"
"5" "educ" "years of schooling"
"6" "married" "=1 if married"
"7" "famsize" "family size"
"8" "white" "=1 if white"
"9" "exhealth" "=1 if in excellent health"
"10" "vghealth" "=1 if in very good health"
"11" "goodhealth" "=1 if in good health"
"12" "fairhealth" "=1 if in fair health"
"13" "northeast" "=1 if live in northeast"
"14" "midwest" "=1 if live in midwest"
"15" "south" "=1 if live in south"
"16" "centcity" "=1 if live in central city of MSA"
"17" "outercity" "=1 if in outer city of MSA"
"18" "qrt1" "=1 if interviewed in first quarter"
"19" "qrt2" "=1 if interviewed in second quarter"
"20" "qrt3" "=1 if interviewed in third quarter"
"21" "beertax" "state excise tax, $ per gallon"
"22" "cigtax" "state cigarette tax, cents per pack"
"23" "ethanol" "state per-capita ethanol consumption"
"24" "mothalc" "=1 if mother an alcoholic"
"25" "fathalc" "=1 if father an alcoholic"
"26" "livealc" "=1 if lived with alcoholic"
"27" "inwf" "=1 if status > 1"
"28" "employ" "=1 if employed"
"29" "agesq" "age^2"
"30" "beertaxsq" "beertax^2"
"31" "cigtaxsq" "cigtax^2"
"32" "ethanolsq" "ethanol^2"
"33" "educsq" "educ^2"
