"variable" "label"
"1" "dscore" "home scr. - vist. scr., 1993"
"2" "dinstt" "diff. in-state tuit., 1994"
"3" "doutstt" "diff. out-state tuit., 1994"
"4" "htpriv" "=1 if home team priv. sch."
"5" "vtpriv" "=1 if vist. team priv. sch."
"6" "dapps" "diff. in applications, 1994"
"7" "htwrd" "=1 if home win. record, 1993"
"8" "vtwrd" "=1 if vist. win. record, 1993"
"9" "dwinrec" "htwrd - vtwrd"
"10" "dpriv" "htpriv - vtpriv"
