"variable" "label"
"1" "attend" "classes attended out of 32"
"2" "termGPA" "GPA for term"
"3" "priGPA" "cumulative GPA prior to term"
"4" "ACT" "ACT score"
"5" "final" "final exam score"
"6" "atndrte" "percent classes attended"
"7" "hwrte" "percent homework turned in"
"8" "frosh" "=1 if freshman"
"9" "soph" "=1 if sophomore"
"10" "missed" "number of classes missed"
"11" "stndfnl" "(final - mean)/sd"
