"variable" "label"
"1" "distid" "district identifier"
"2" "schid" "school identifier"
"3" "lunch" "percent eligible, free lunch"
"4" "enroll" "school enrollment"
"5" "staff" "staff per 1000 students"
"6" "exppp" "expenditures per pupil"
"7" "avgsal" "average teacher salary, $"
"8" "avgben" "average teacher non-salary benefits, $"
"9" "math4" "percent passing 4th grade math test"
"10" "story4" "percent passing 4th grade reading test"
"11" "bs" "avgben/avgsal"
"12" "lavgsal" "log(avgsal)"
"13" "lenroll" "log(enroll)"
"14" "lstaff" "log(staff)"
"15" "bsbar" "within-district avg of bs"
"16" "lunchbar" "within-district avg of lunch"
"17" "lenrollbar" "within-district avg of lenroll"
"18" "lstaffbar" "within-district avg of lstaff"
