"variable" "label"
"1" "month" "dec 200 through feb 2012"
"2" "urate" "unemployment rate, percent"
"3" "vrate" "vacancy rate, percent"
"4" "t" "linear time trend"
"5" "urate_1" "L.urate"
"6" "vrate_1" "L.vrate"
"7" "curate" "D.urate"
"8" "cvrate" "D.vrate"
