"variable" "label"
"1" "id" "person identifier"
"2" "year" "92, 95, or 99"
"3" "salary" "annual salary, $"
"4" "pubindx" "publication index"
"5" "totpge" "standardized total article pages"
"6" "assist" "=1 if assistant professor"
"7" "assoc" "=1 if associate professor"
"8" "prof" "=1 if full professor"
"9" "chair" "=1 if department chair"
"10" "top20phd" "=1 if Ph.D. from top 20 dept."
"11" "yearphd" "year Ph.D. obtained"
"12" "female" "=1 if female"
"13" "osu" "=1 if Ohio State U."
"14" "iowa" "=1 if U. Iowa"
"15" "indiana" "=1 if Indiana U."
"16" "purdue" "=1 if Purdue U."
"17" "msu" "=1 if Michigan State U."
"18" "minn" "=1 if U. Minnesota"
"19" "mich" "=1 if U. Michigan"
"20" "wisc" "=1 if U. Wisconsin"
"21" "illinois" "=1 if U. Illinois"
"22" "y92" "=1 if year == 92"
"23" "y95" "=1 if year == 95"
"24" "y99" "=1 if year == 99"
"25" "lsalary" "log(salary)"
"26" "exper" "years since first teaching job"
"27" "expersq" "exper^2"
"28" "pubindxsq" "pubindx^2"
"29" "pubindx0" "=1 if pubindx == 0"
"30" "lpubindx" "log(pubindx) if pubindx > 0"
