"variable" "label"
"1" "year" "1947 to 1987"
"2" "wkearns" "avg. real weekly earnings"
"3" "wkhours" "avg. weekly hours"
"4" "outphr" "output per labor hour"
"5" "hrwage" "wkearns/wkhours"
"6" "lhrwage" "log(hrwage)"
"7" "loutphr" "log(outphr)"
"8" "t" "time trend:  t=1 to 47"
"9" "ghrwage" "lhrwage - lhrwage[_n-1]"
"10" "goutphr" "loutphr - loutphr[_n-1]"
"11" "ghrwge_1" "ghrwage[_n-1]"
"12" "goutph_1" "goutphr[_n-1]"
"13" "goutph_2" "goutphr[_n-2]"
"14" "lwkhours" "log(wkhours)"
