"variable" "label"
"1" "sfood" "share of food expenditures (out of total)"
"2" "sfuel" "share of fuel expenditures"
"3" "sclothes" "share of clothing expenditures"
"4" "salcohol" "share of alcohol expenditures"
"5" "stransport" "share of transportation expenditures"
"6" "sother" "share of other expenditures"
"7" "totexpend" "total expenditure, British pounds per week"
"8" "income" "family income, British pounds per week"
"9" "age" "age of household head"
"10" "kids" "number of children: 1 or 2"
"11" "ltotexpend" "log(totexpend)"
"12" "lincome" "log(income)"
"13" "agesq" "age^2"
