"variable" "label"
"1" "annearn" "annual earnings, $"
"2" "hrearn" "hourly earnings, $"
"3" "exper" "years work experience"
"4" "age" "age in years"
"5" "depends" "number of dependents"
"6" "married" "=1 if married"
"7" "tenure" "years with current employer"
"8" "educ" "years schooling"
"9" "nrtheast" "=1 if live in northeast"
"10" "nrthcen" "=1 if live in north central"
"11" "south" "=1 if live in south"
"12" "male" "=1 if male"
"13" "white" "=1 if white"
"14" "union" "=1 if union member"
"15" "office" ""
"16" "annhrs" "annual hours worked"
"17" "ind1" "industry dummy"
"18" "ind2" ""
"19" "ind3" ""
"20" "ind4" ""
"21" "ind5" ""
"22" "ind6" ""
"23" "ind7" ""
"24" "ind8" ""
"25" "ind9" ""
"26" "vacdays" "$ value of vac. days"
"27" "sicklve" "$ value of sick leave"
"28" "insur" "$ value of employee insur"
"29" "pension" "$ value of employee pension"
"30" "annbens" "vacdays+sicklve+insur+pension"
"31" "hrbens" "hourly benefits, $"
"32" "annhrssq" "annhrs^2"
"33" "beratio" "annbens/annearn"
"34" "lannhrs" "log(annhrs)"
"35" "tenuresq" "tenure^2"
"36" "expersq" "exper^2"
"37" "lannearn" "log(annearn)"
"38" "peratio" "pension/annearn"
"39" "vserat" "(vacdays+sicklve)/annearn"
