"variable" "label"
"1" "sat" "combined SAT score"
"2" "tothrs" "total hours through fall semest"
"3" "colgpa" "GPA after fall semester"
"4" "athlete" "=1 if athlete"
"5" "verbmath" "verbal/math SAT score"
"6" "hsize" "size grad. class, 100s"
"7" "hsrank" "rank in grad. class"
"8" "hsperc" "high school percentile, from top"
"9" "female" "=1 if female"
"10" "white" "=1 if white"
"11" "black" "=1 if black"
"12" "hsizesq" "hsize^2"
