"variable" "label"
"1" "price" "median housing price, $"
"2" "crime" "crimes committed per capita"
"3" "nox" "nit ox concen; parts per 100m"
"4" "rooms" "avg number of rooms"
"5" "dist" "wght dist to 5 employ centers"
"6" "radial" "access. index to rad. hghwys"
"7" "proptax" "property tax per $1000"
"8" "stratio" "average student-teacher ratio"
"9" "lowstat" "perc of people 'lower status'"
"10" "lprice" "log(price)"
"11" "lnox" "log(nox)"
"12" "lproptax" "log(proptax)"
