"variable" "label"
"1" "year" "1947-1988"
"2" "inv" "real housing inv, millions $"
"3" "pop" "population, 1000s"
"4" "price" "housing price index; 1982 = 1"
"5" "linv" "log(inv)"
"6" "lpop" "log(pop)"
"7" "lprice" "log(price)"
"8" "t" "time trend: t=1,...,42"
"9" "invpc" "per capita inv: inv/pop"
"10" "linvpc" "log(invpc)"
"11" "lprice_1" "lprice[_n-1]"
"12" "linvpc_1" "linvpc[_n-1]"
"13" "gprice" "lprice - lprice_1"
"14" "ginvpc" "linvpc - linvpc_1"
