"variable" "label"
"1" "durat" "duration of benefits"
"2" "afchnge" "=1 if after change in benefits"
"3" "highearn" "=1 if high earner"
"4" "male" "=1 if male"
"5" "married" "=1 if married"
"6" "hosp" "=1 if inj. required hosp. stay"
"7" "indust" "industry"
"8" "injtype" "type of injury"
"9" "age" "age at time of injury"
"10" "prewage" "previous weekly wage, 1982 $"
"11" "totmed" "total med. costs, 1982 $"
"12" "injdes" "4 digit injury description"
"13" "benefit" "real dollar value of benefit"
"14" "ky" "=1 for kentucky"
"15" "mi" "=1 for michigan"
"16" "ldurat" "log(durat)"
"17" "afhigh" "afchnge*highearn"
"18" "lprewage" "log(wage)"
"19" "lage" "log(age)"
"20" "ltotmed" "log(totmed); = 0 if totmed < 1"
"21" "head" "=1 if head injury"
"22" "neck" "=1 if neck injury"
"23" "upextr" "=1 if upper extremities injury"
"24" "trunk" "=1 if trunk injury"
"25" "lowback" "=1 if lower back injury"
"26" "lowextr" "=1 if lower extremities injury"
"27" "occdis" "=1 if occupational disease"
"28" "manuf" "=1 if manufacturing industry"
"29" "construc" "=1 if construction industry"
"30" "highlpre" "highearn*lprewage"
