"variable" "label"
"1" "year" "1978 or 1981"
"2" "age" "age of house"
"3" "agesq" "age^2"
"4" "nbh" "neighborhood, 1-6"
"5" "cbd" "dist. to cent. bus. dstrct, ft."
"6" "intst" "dist. to interstate, ft."
"7" "lintst" "log(intst)"
"8" "price" "selling price"
"9" "rooms" "# rooms in house"
"10" "area" "square footage of house"
"11" "land" "square footage lot"
"12" "baths" "# bathrooms"
"13" "dist" "dist. from house to incin., ft."
"14" "ldist" "log(dist)"
"15" "wind" "prc. time wind incin. to house"
"16" "lprice" "log(price)"
"17" "y81" "=1 if year == 1981"
"18" "larea" "log(area)"
"19" "lland" "log(land)"
"20" "y81ldist" "y81*ldist"
"21" "lintstsq" "lintst^2"
"22" "nearinc" "=1 if dist <= 15840"
"23" "y81nrinc" "y81*nearinc"
"24" "rprice" "price, 1978 dollars"
"25" "lrprice" "log(rprice)"
