"variable" "label"
"1" "year" "1987 or 1990"
"2" "lowbrth" "perc births low weight"
"3" "infmort" "infant mortality rate"
"4" "afdcprt" "# participants in AFDC, 1000s"
"5" "popul" "population, 1000s"
"6" "pcinc" "per capita income"
"7" "physic" "# physicians, 1000s"
"8" "afdcprc" "percent of pop in AFDC"
"9" "d90" "=1 if year == 1990"
"10" "lpcinc" "log of pcinc"
"11" "cafdcprc" "change in afdcprc"
"12" "clpcinc" "change in lpcinc"
"13" "lphysic" "log of physic"
"14" "clphysic" "change in lphysic"
"15" "clowbrth" "change in lowbrth"
"16" "cinfmort" "change in infmort"
"17" "afdcpay" "avg monthly AFDC payment"
"18" "afdcinc" "afdcpay as % pcinc"
"19" "lafdcpay" "log of afdcpay"
"20" "clafdcpy" "change in lafdcpay"
"21" "cafdcinc" "change in afdcinc"
"22" "stateabb" "state postal code"
"23" "state" "name of state"
"24" "beds" "# hospital beds, 1000s"
"25" "bedspc" "beds per capita"
"26" "lbedspc" "log(bedspc)"
"27" "clbedspc" "change in lbedspc"
"28" "povrate" "% people below poverty line"
"29" "cpovrate" "change in povrate"
"30" "afdcpsq" "afdcper^2"
"31" "cafdcpsq" "change in afdcpsq"
"32" "physicpc" "physicians per capita"
"33" "lphypc" "log(physicpc)"
"34" "clphypc" "change in lphypc"
"35" "lpopul" "log(popul)"
"36" "clpopul" "change in lpopul"
