"variable" "label"
"1" "inlf" "=1 if in lab frce, 1975"
"2" "hours" "hours worked, 1975"
"3" "kidslt6" "# kids < 6 years"
"4" "kidsge6" "# kids 6-18"
"5" "age" "woman's age in yrs"
"6" "educ" "years of schooling"
"7" "wage" "est. wage from earn, hrs"
"8" "repwage" "rep. wage at interview in 1976"
"9" "hushrs" "hours worked by husband, 1975"
"10" "husage" "husband's age"
"11" "huseduc" "husband's years of schooling"
"12" "huswage" "husband's hourly wage, 1975"
"13" "faminc" "family income, 1975"
"14" "mtr" "fed. marg. tax rte facing woman"
"15" "motheduc" "mother's years of schooling"
"16" "fatheduc" "father's years of schooling"
"17" "unem" "unem. rate in county of resid."
"18" "city" "=1 if live in SMSA"
"19" "exper" "actual labor mkt exper"
"20" "nwifeinc" "(faminc - wage*hours)/1000"
"21" "lwage" "log(wage)"
"22" "expersq" "exper^2"
