"variable" "label"
"1" "price" "NYSE stock price index"
"2" "return" "100*(p - p(-1))/p(-1))"
"3" "return_1" "lagged return"
"4" "t" ""
"5" "price_1" ""
"6" "price_2" ""
"7" "cprice" "price - price_1"
"8" "cprice_1" "lagged cprice"
