"variable" "label"
"1" "year" "1950-1987"
"2" "avgmin" "weighted avg min wge, 44 indust"
"3" "avgwage" "wghted avg hrly wge, 44 indust"
"4" "kaitz" "Kaitz min wage index"
"5" "avgcov" "wghted avg coverage, 8 indust"
"6" "covt" "economy-wide coverage of min wg"
"7" "mfgwage" "avg manuf. wage"
"8" "prdef" "Puerto Rican price deflator"
"9" "prepop" "PR employ/popul ratio"
"10" "prepopf" "PR employ/popul ratio, alter."
"11" "prgnp" "PR GNP"
"12" "prunemp" "PR unemployment rate"
"13" "usgnp" "US GNP"
"14" "t" "time trend:  1 to 38"
"15" "post74" "time trend:  starts in 1974"
"16" "lprunemp" "log(prunemp)"
"17" "lprgnp" "log(prgnp)"
"18" "lusgnp" "log(usgnp)"
"19" "lkaitz" "log(kaitz)"
"20" "lprun_1" "lprunemp[_n-1]"
"21" "lprepop" "log(prepop)"
"22" "lprep_1" "lprepop[_n-1]"
"23" "mincov" "(avgmin/avgwage)*avgcov"
"24" "lmincov" "log(mincov)"
"25" "lavgmin" "log(avgmin)"
