"variable" "label"
"1" "rd" "R&D spending, millions"
"2" "sales" "firm sales, millions"
"3" "profits" "profits, millions"
"4" "rdintens" "rd as percent of sales"
"5" "profmarg" "profits as percent of sales"
"6" "salessq" "sales^2"
"7" "lsales" "log(sales)"
"8" "lrd" "log(rd)"
