"variable" "label"
"1" "age" "in years"
"2" "black" "=1 if black"
"3" "case" "identifier"
"4" "clerical" "=1 if clerical worker"
"5" "construc" "=1 if construction worker"
"6" "educ" "years of schooling"
"7" "earns74" "total earnings, 1974"
"8" "gdhlth" "=1 if in good or excel. health"
"9" "inlf" "=1 if in labor force"
"10" "leis1" "sleep - totwrk"
"11" "leis2" "slpnaps - totwrk"
"12" "leis3" "rlxall - totwrk"
"13" "smsa" "=1 if live in smsa"
"14" "lhrwage" "log hourly wage"
"15" "lothinc" "log othinc, unless othinc < 0"
"16" "male" "=1 if male"
"17" "marr" "=1 if married"
"18" "prot" "=1 if Protestant"
"19" "rlxall" "slpnaps + personal activs"
"20" "selfe" "=1 if self employed"
"21" "sleep" "mins sleep at night, per wk"
"22" "slpnaps" "minutes sleep, inc. naps"
"23" "south" "=1 if live in south"
"24" "spsepay" "spousal wage income"
"25" "spwrk75" "=1 if spouse works"
"26" "totwrk" "mins worked per week"
"27" "union" "=1 if belong to union"
"28" "worknrm" "mins work main job"
"29" "workscnd" "mins work second job"
"30" "exper" "age - educ - 6"
"31" "yngkid" "=1 if children < 3 present"
"32" "yrsmarr" "years married"
"33" "hrwage" "hourly wage"
"34" "agesq" "age^2"
