"variable" "label"
"1" "educ" "years of schooling"
"2" "cigpric" "state cig. price, cents/pack"
"3" "white" "=1 if white"
"4" "age" "in years"
"5" "income" "annual income, $"
"6" "cigs" "cigs. smoked per day"
"7" "restaurn" "=1 if rest. smk. restrictions"
"8" "lincome" "log(income)"
"9" "agesq" "age^2"
"10" "lcigpric" "log(cigprice)"
