"variable" "label"
"1" "year" "1981 to 1989"
"2" "totacc" "statewide total accidents"
"3" "fatacc" "statewide fatal accidents"
"4" "injacc" "statewide injury accidents"
"5" "pdoacc" "property damage only accidents"
"6" "ntotacc" "noninterstate total acc."
"7" "nfatacc" "noninterstate fatal acc."
"8" "ninjacc" "noninterstate injur acc."
"9" "npdoacc" "noninterstate property acc."
"10" "rtotacc" "tot. acc. on rural 65 mph roads"
"11" "rfatacc" "fat. acc. on rural 65 mph roads"
"12" "rinjacc" "inj. acc. on rural 65 mph roads"
"13" "rpdoacc" "prp. acc. on rural 65 mph roads"
"14" "ushigh" "acc. on U.S. highways"
"15" "cntyrds" "acc. on county roads"
"16" "strtes" "acc. on state routes"
"17" "t" "time trend"
"18" "tsq" "t^2"
"19" "unem" "state unemployment rate"
"20" "spdlaw" "=1 after 65 mph in effect"
"21" "beltlaw" "=1 after seatbelt law"
"22" "wkends" "# weekends in month"
"23" "feb" "=1 if month is Feb."
"24" "mar" ""
"25" "apr" ""
"26" "may" ""
"27" "jun" ""
"28" "jul" ""
"29" "aug" ""
"30" "sep" ""
"31" "oct" ""
"32" "nov" ""
"33" "dec" ""
"34" "ltotacc" "log(totacc)"
"35" "lfatacc" "log(fatacc)"
"36" "prcfat" "100*(fatacc/totacc)"
"37" "prcrfat" "100*(rfatacc/rtotacc)"
"38" "lrtotacc" "log(rtotacc)"
"39" "lrfatacc" "log(rfatacc)"
"40" "lntotacc" "log(ntotacc)"
"41" "lnfatacc" "log(nfatacc)"
"42" "prcnfat" "100*(nfatacc/ntotacc)"
"43" "lushigh" "log(ushigh)"
"44" "lcntyrds" "log(cntyrds)"
"45" "lstrtes" "log(strtes)"
"46" "spdt" "spdlaw*t"
"47" "beltt" "beltlaw*t"
"48" "prcfat_1" "prcfat[_n-1]"
