"variable" "label"
"1" "state" "state postal code"
"2" "district" "congressional district"
"3" "democA" "=1 if A is democrat"
"4" "voteA" "percent vote for A"
"5" "expendA" "camp. expends. by A, $1000s"
"6" "expendB" "camp. expends. by B, $1000s"
"7" "prtystrA" "% vote for president"
"8" "lexpendA" "log(expendA)"
"9" "lexpendB" "log(expendB)"
"10" "shareA" "100*(expendA/(expendA+expendB))"
