"variable" "label"
"1" "studyid" "student identifier"
"2" "black" "= 1 if African-American"
"3" "hispanic" "= 1 if Hispanic"
"4" "female" "= 1 if female"
"5" "appyear" "year of first application: 90 to 93"
"6" "mnce" "math NCE test score, 1994"
"7" "select" "= 1 if ever selected to attend choice school"
"8" "choice" "= 1 if attending choice school, 1994"
"9" "selectyrs" "years selected to attend choice school"
"10" "choiceyrs" "years attended choice school"
"11" "mnce90" "mnce in 1990"
"12" "selectyrs1" "= 1 if selectyrs == 1"
"13" "selectyrs2" "= 1 if selectyrs == 2"
"14" "selectyrs3" "= 1 if selectyrs == 3"
"15" "selectyrs4" "= 1 if selectyrs == 4"
"16" "choiceyrs1" "= 1 if choiceyrs == 1"
"17" "choiceyrs2" "= 1 if choiceyrs == 2"
"18" "choiceyrs3" "= 1 if choiceyrs == 3"
"19" "choiceyrs4" "= 1 if choiceyrs == 4"
